import { ArrowLeft, ArrowRight, Search, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { campaigns } from "@/lib/vuze-data";

const LOGO = "/manus-storage/vuze-logo_0bd65c44.png";
function Header() { return <header className="topbar"><div className="topbar-inner"><Link href="/" className="brand"><img src={LOGO} alt="" /><span>vuze</span></Link><nav className="nav-links"><Link className="active" href="/campaigns">Campaigns</Link><Link href="/learn">Creator resources</Link></nav><div className="nav-actions"><Link href="/dashboard" className="btn btn-dark btn-sm">Creator workspace <ArrowRight size={14} /></Link></div></div></header>; }

export default function CampaignDetail() {
  const [, params] = useRoute("/campaigns/:id");
  const campaign = campaigns.find((item) => item.id === params?.id);
  if (!campaign) return <><Header /><main className="page-wrap"><section className="marketplace-empty detail-empty"><div className="workspace-empty-icon"><Search size={18} /></div><h1>This campaign isn’t available.</h1><p>No live campaign details are published at this address. Visit the marketplace to see available opportunities.</p><Link className="btn btn-light btn-sm" href="/campaigns"><ArrowLeft size={13} /> Back to campaigns</Link></section></main><footer className="footer"><div className="page-wrap footer-inner"><span>© 2026 VUZE</span><Link href="/">Back to home</Link></div></footer></>;
  return <><Header /><main className="page-wrap"><div className="page-heading" style={{ paddingBottom: 24 }}><Link href="/campaigns" className="btn-plain" style={{ display: "inline-flex", alignItems: "center", gap: 6 }}><ArrowLeft size={13} /> All campaigns</Link></div><div className="detail-layout"><section className="detail-main"><div className="detail-title-row"><span className="project-mark" style={{ background: campaign.accent, width: 54, height: 54, fontSize: 19 }}>{campaign.name.slice(0, 1)}</span><div><div className="tag">{campaign.category}</div><h1 style={{ marginTop: 7 }}>{campaign.name}</h1><span style={{ color: "#85857f", fontSize: 11 }}>{campaign.ticker}</span></div></div><div className="detail-section"><p style={{ color: "#686862", fontSize: 13, lineHeight: 1.75 }}>{campaign.description}</p><div className="platform-list">{campaign.platforms.map((item) => <span className="platform-chip" key={item}>{item}</span>)}{campaign.tags.map((item) => <span className="tag" key={item}>{item}</span>)}</div></div><div className="detail-section"><h2>Creator guidelines</h2><p>Follow the published brief and platform disclosure rules. Keep creative original, accurate, and in your own voice.</p><ul><li>Do not make financial promises, price guarantees, or misleading claims.</li><li>Disclose paid partnerships as required by the platform and local rules.</li><li>Check final campaign eligibility and review terms before posting.</li></ul></div><div className="detail-section"><h2>Trust & review</h2><p>Any future review process should share clear reasons and provide a way to request reconsideration.</p><div className="notice" style={{ marginTop: 13 }}><ShieldCheck size={15} style={{ display: "inline", verticalAlign: "middle", marginRight: 7, color: "#287458" }} /><strong>Creator-facing clarity matters.</strong> No social verification, view tracking, or campaign-specific review flow is connected yet.</div></div></section><aside className="detail-aside"><div className="eyebrow"><span className="eyebrow-dot" /> Campaign terms</div><div className="aside-rate">${campaign.rate.toFixed(2)} <small>/ 1,000 views</small></div>{[["Budget remaining", `$${campaign.remaining.toLocaleString()}`],["Minimum views", campaign.minViews.toLocaleString()],["Maximum per video", `$${campaign.maxPayout}`],["Deadline", campaign.deadline],["Allowed platforms", campaign.platforms.join(", ")]].map(([label, value]) => <div className="aside-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}<div className="notice" style={{ marginTop: 14 }}>Posting and payout actions become available after production integrations are enabled.</div></aside></div></main><footer className="footer"><div className="page-wrap footer-inner"><span>© 2026 VUZE</span><Link href="/campaigns">Back to campaigns</Link></div></footer></>;
}
