import { useMemo, useState } from "react";
import { ArrowRight, Search } from "lucide-react";
import { Link } from "wouter";
import { campaigns } from "@/lib/vuze-data";

const LOGO = "/manus-storage/vuze-logo_0bd65c44.png";
function Nav() { return <header className="topbar"><div className="topbar-inner"><Link href="/" className="brand"><img src={LOGO} alt="" /><span>vuze</span></Link><nav className="nav-links"><Link className="active" href="/campaigns">Campaigns</Link><Link href="/learn">Creator resources</Link><a href="/#how">How it works</a></nav><div className="nav-actions"><Link className="nav-login" href="/dashboard">Creator workspace</Link><Link className="btn btn-dark btn-sm" href="/dashboard">Open workspace <ArrowRight size={14} /></Link></div></div></header>; }

export default function Campaigns() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All categories");
  const [platform, setPlatform] = useState("All platforms");
  const categories = ["All categories", ...Array.from(new Set(campaigns.map((item) => item.category)))];
  const filtered = useMemo(() => campaigns.filter((item) => {
    const matchesQuery = `${item.name} ${item.ticker} ${item.category} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (category === "All categories" || item.category === category) && (platform === "All platforms" || item.platforms.includes(platform));
  }), [query, category, platform]);
  return <><Nav /><main className="page-wrap"><div className="page-heading"><div className="eyebrow"><span className="eyebrow-dot" /> Campaign marketplace</div><h1>Find your next brief.</h1><p>Browse opportunities, compare published terms, and choose a format that fits your audience.</p></div>
    {campaigns.length > 0 ? <><div className="filters-bar"><label className="search-field"><Search size={15} /><input aria-label="Search campaigns" placeholder="Search campaigns, topics, or tokens" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select className="filter-select" aria-label="Filter by category" value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select><select className="filter-select" aria-label="Filter by platform" value={platform} onChange={(event) => setPlatform(event.target.value)}>{["All platforms", "TikTok", "Reels", "Shorts", "X"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="listing-count">Showing <strong style={{ color: "#292925" }}>{filtered.length}</strong> campaigns</div>{filtered.length ? <div className="campaign-grid" style={{ paddingBottom: 72 }}>{filtered.map((item) => <article className="campaign-card" key={item.id}><div className="campaign-top"><span className="project-mark" style={{ background: item.accent }}>{item.name.slice(0, 1)}</span><span className="tag">{item.category}</span></div><h2 className="campaign-title">{item.name}</h2><div className="campaign-ticker">{item.ticker}</div><p className="campaign-desc">{item.description}</p><div className="campaign-meta"><div><div className="meta-label">Rate / 1,000 views</div><div className="meta-value">${item.rate.toFixed(2)}</div></div><div><div className="meta-label">Budget left</div><div className="meta-value">${item.remaining.toLocaleString()}</div></div><div><div className="meta-label">Minimum views</div><div className="meta-value">{item.minViews.toLocaleString()}</div></div><div><div className="meta-label">Maximum / video</div><div className="meta-value">${item.maxPayout}</div></div></div><div className="platform-list">{item.platforms.map((itemPlatform) => <span className="platform-chip" key={itemPlatform}>{itemPlatform}</span>)}</div><Link className="card-link" href={`/campaigns/${item.id}`}>Campaign details <ArrowRight size={14} /></Link></article>)}</div> : <div className="empty-state">No campaigns match those filters. Try another search.</div>}</> : <section className="marketplace-empty"><div className="workspace-empty-icon"><Search size={20} /></div><h2>No campaigns are live yet.</h2><p>New opportunities will appear here when campaign details and terms are ready to publish.</p><Link className="btn btn-light btn-sm" href="/learn">Explore creator resources <ArrowRight size={13} /></Link></section>}
  </main><footer className="footer"><div className="page-wrap footer-inner"><span>© 2026 VUZE</span><Link href="/">Back to home</Link></div></footer></>;
}
