import { ArrowRight, BadgeCheck, BookOpen, ClipboardList, ExternalLink, FileCheck2, LayoutDashboard, Search, ShieldCheck, Trophy, Wallet } from "lucide-react";
import { Link, useLocation } from "wouter";

const LOGO = "/manus-storage/vuze-logo_0bd65c44.png";
const navItems = [
  { path: "/dashboard", label: "Home", icon: LayoutDashboard },
  { path: "/campaigns", label: "Campaigns", icon: Search },
  { path: "/clips", label: "My campaigns", icon: ClipboardList },
  { path: "/leaderboard", label: "Leaderboard", icon: Trophy },
  { path: "/earnings", label: "Earnings", icon: Wallet },
  { path: "/profile", label: "Profile", icon: BadgeCheck },
];

export default function CreatorDashboard() {
  const [location] = useLocation();
  const pageName = location === "/clips" ? "My campaigns" : location === "/earnings" ? "Earnings" : location === "/profile" ? "Profile" : location === "/leaderboard" ? "Leaderboard" : "Home";
  const isOverview = location === "/dashboard" || location === "/";
  return <div className="workspace"><aside className="workspace-side"><div className="workspace-logo"><Link href="/" className="brand"><img src={LOGO} alt="" /><span>vuze</span></Link></div><div className="side-caption">General</div>{navItems.slice(0, 2).map(({ path, label, icon: Icon }) => <Link key={path} href={path} className={`side-link ${location === path || (path === "/dashboard" && location === "/") ? "active" : ""}`}><Icon />{label}</Link>)}<div className="side-caption" style={{ marginTop: 15 }}>Activity</div>{navItems.slice(2).map(({ path, label, icon: Icon }) => <Link key={path} href={path} className={`side-link ${location === path ? "active" : ""}`}><Icon />{label}</Link>)}<div className="side-caption" style={{ marginTop: 15 }}>Support</div><Link href="/learn" className="side-link"><BookOpen />Creator resources</Link><Link href="/review" className="side-link"><FileCheck2 />Trust & safety</Link></aside>
    <div className="workspace-main"><header className="workspace-top"><div className="crumb"><span style={{ color: "#a6d900", fontWeight: 800, letterSpacing: ".12em", fontSize: 9 }}>VUZE</span><span style={{ color: "#656866", margin: "0 9px" }}>/</span>{pageName}</div><div className="top-right"><span className="dash-alpha">VUZE</span><Link href="/" className="btn-plain">Public site <ExternalLink size={12} style={{ verticalAlign: "middle" }} /></Link></div></header><main className="workspace-content"><div className="workspace-title-row"><div><div className="eyebrow"><span className="eyebrow-dot" /> Creator workspace</div><h1 style={{ marginTop: 7 }}>{isOverview ? "Your creator space." : pageName}</h1><p>Your campaigns, submissions, and account details will appear here when they’re available.</p></div>{isOverview && <Link className="btn btn-lime" href="/campaigns">Browse campaigns <ArrowRight size={14} /></Link>}</div>
      {isOverview && <><section className="workspace-empty-hero"><div className="workspace-empty-icon"><ShieldCheck size={21} /></div><div><span className="empty-kicker">Workspace status</span><h2>Nothing to show yet.</h2><p>There are no live campaigns or creator records connected to this workspace. When VUZE connects its campaign and social platforms, real account activity will appear here.</p><Link className="inline-link" href="/campaigns">See campaign availability <ArrowRight size={13} /></Link></div></section><div className="workspace-grid empty-panels"><section className="panel"><div className="panel-head"><h2>Campaigns</h2><Search size={15} /></div><div className="section-empty"><strong>No campaigns published</strong><span>Available briefs will appear here.</span></div></section><section className="panel"><div className="panel-head"><h2>Submissions</h2><ClipboardList size={15} /></div><div className="section-empty"><strong>No clips submitted</strong><span>Submissions will appear after the review flow is connected.</span></div></section><section className="panel"><div className="panel-head"><h2>Earnings</h2><Wallet size={15} /></div><div className="section-empty"><strong>No earnings recorded</strong><span>Payments are not connected yet.</span></div></section></div><section className="panel workspace-trust-note"><div className="panel-head"><h2>Trust & safety</h2><ShieldCheck size={15} /></div><p>Account ownership checks, view-anomaly signals, clear review reasons, and human review are planned parts of the product. They are not connected in this workspace yet.</p><Link href="/review" className="btn btn-light btn-sm">View review principles <ArrowRight size={13} /></Link></section></>}
      {location === "/leaderboard" && <section className="panel route-empty"><div className="workspace-empty-icon"><Trophy size={20} /></div><h2>No rankings published.</h2><p>Creator rankings will appear when verified activity is available and leaderboard participation is enabled.</p></section>}
      {location === "/clips" && <section className="panel route-empty"><div className="workspace-empty-icon"><ClipboardList size={20} /></div><h2>No submissions yet.</h2><p>Creator submissions will appear here once campaigns and the review flow are connected.</p><Link className="btn btn-light btn-sm" href="/campaigns">Browse campaigns <ArrowRight size={13} /></Link></section>}
      {location === "/earnings" && <section className="panel route-empty"><div className="workspace-empty-icon"><Wallet size={20} /></div><h2>No earnings available.</h2><p>Earnings information will appear after eligible activity and a payout provider are connected. No payment account is linked.</p></section>}
      {location === "/profile" && <section className="panel route-empty"><div className="workspace-empty-icon"><BadgeCheck size={20} /></div><h2>No social accounts connected.</h2><p>Account linking and ownership verification will be available when the approved platform authorization flows are integrated.</p></section>}
      <div className="workspace-footnote">No campaign, creator, submission, moderation, or earnings records are loaded in this workspace.</div>
    </main></div></div>;
}
