import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BadgeCheck, BookOpen, CircleHelp, ClipboardList, Coins, ExternalLink, FileCheck2, LayoutDashboard, Plus, Search, ShieldCheck, Trophy, Wallet, X } from "lucide-react";
import { Link, useLocation } from "wouter";
import { campaigns, monthlyLeaderboard, sampleClips, type Clip, weeklyLeaderboard } from "@/lib/vuze-data";

const LOGO = "/manus-storage/vuze-logo_0bd65c44.png";
const navItems = [
  { path: "/dashboard", label: "Home", icon: LayoutDashboard },
  { path: "/campaigns", label: "Campaigns", icon: Search },
  { path: "/clips", label: "My campaigns", icon: ClipboardList },
  { path: "/leaderboard", label: "Leaderboard", icon: Trophy },
  { path: "/earnings", label: "Earnings", icon: Wallet },
  { path: "/profile", label: "Profile", icon: BadgeCheck },
];
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value);

export default function CreatorDashboard() {
  const [location] = useLocation();
  const [submissions, setSubmissions] = useState<Clip[]>(() => { try { return JSON.parse(localStorage.getItem("vuze-demo-submissions") || "[]") as Clip[]; } catch { return []; } });
  const [modal, setModal] = useState(false);
  const [url, setUrl] = useState("");
  const [selectedCampaign, setSelectedCampaign] = useState(() => new URLSearchParams(window.location.search).get("campaign") || campaigns[0].id);
  const [toast, setToast] = useState("");
  const [connected, setConnected] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("vuze-demo-socials") || '["TikTok"]') as string[]; } catch { return ["TikTok"]; } });
  const [leaderPeriod, setLeaderPeriod] = useState<"This week" | "This month">("This week");
  const [anonymous, setAnonymous] = useState(false);
  const allClips = useMemo(() => [...submissions, ...sampleClips], [submissions]);
  const pageName = location === "/clips" ? "My campaigns" : location === "/earnings" ? "Earnings" : location === "/profile" ? "Profile" : location === "/leaderboard" ? "Leaderboard" : "Home";
  const leaderboard = leaderPeriod === "This week" ? weeklyLeaderboard : monthlyLeaderboard;
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 3200); return () => window.clearTimeout(timer); }, [toast]);

  function submitClip(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const cleanUrl = url.trim();
    if (!/^https?:\/\//i.test(cleanUrl) || !/(tiktok\.com|instagram\.com|youtube\.com|youtu\.be|x\.com|twitter\.com)/i.test(cleanUrl)) { setToast("Enter a public TikTok, Instagram, YouTube, or X link."); return; }
    const campaign = campaigns.find((item) => item.id === selectedCampaign) || campaigns[0];
    const platform = /instagram/i.test(cleanUrl) ? "Instagram" : /youtube|youtu\.be/i.test(cleanUrl) ? "YouTube" : /tiktok/i.test(cleanUrl) ? "TikTok" : "X";
    const item: Clip = { id: `DEMO-${Date.now().toString().slice(-5)}`, campaign: campaign.name, platform, views: 0, earned: 0, status: "Under review", submitted: "Just now" };
    const next = [item, ...submissions]; setSubmissions(next); localStorage.setItem("vuze-demo-submissions", JSON.stringify(next)); setUrl(""); setModal(false); setToast("Demo clip added to this browser’s review queue.");
  }
  function requestPayout() { setToast("Payout requests are a prototype interaction — no money was moved."); }
  function toggleSocial(platform: string) { const next = connected.includes(platform) ? connected.filter((item) => item !== platform) : [...connected, platform]; setConnected(next); localStorage.setItem("vuze-demo-socials", JSON.stringify(next)); }

  return <div className="workspace"><aside className="workspace-side"><div className="workspace-logo"><Link href="/" className="brand"><img src={LOGO} alt="" /><span>vuze</span></Link></div><div className="side-caption">General</div>{navItems.slice(0, 2).map(({ path, label, icon: Icon }) => <Link key={path} href={path} className={`side-link ${location === path || (path === "/dashboard" && location === "/") ? "active" : ""}`}><Icon />{label}</Link>)}<div className="side-caption" style={{ marginTop: 15 }}>Activity</div>{navItems.slice(2).map(({ path, label, icon: Icon }) => <Link key={path} href={path} className={`side-link ${location === path ? "active" : ""}`}><Icon />{label}</Link>)}<div className="side-caption" style={{ marginTop: 15 }}>Support</div><Link href="/learn" className="side-link"><BookOpen />Creator resources</Link><Link href="/review" className="side-link"><FileCheck2 />Trust review</Link><div className="side-bottom"><div className="profile-chip"><div className="profile-avatar">A</div><div><div className="profile-name">Alex Morgan</div><div className="profile-level">Creator · Demo account</div></div></div></div></aside>
    <div className="workspace-main"><header className="workspace-top"><div className="crumb"><span style={{ color: "#a6d900", fontWeight: 800, letterSpacing: ".12em", fontSize: 9 }}>VUZE</span><span style={{ color: "#656866", margin: "0 9px" }}>/</span>{pageName}</div><div className="top-right"><span className="dash-alpha">✦ ALPHA</span><span className="live-demo"><i /> Demo data</span><Link href="/earnings" className="dash-wallet"><Wallet size={13} />{money(426.8)}</Link><span className="top-avatar">A</span></div></header><main className="workspace-content"><div className="workspace-title-row"><div><div className="eyebrow"><span className="eyebrow-dot" /> Creator space · illustrative data</div><h1 style={{ marginTop: 7 }}>{location === "/dashboard" || location === "/" ? "Welcome back, Alex." : pageName}</h1><p>{location === "/leaderboard" ? "A little friendly competition, built around real creative work." : "Your campaigns, clips, and earnings — all in one place."} Figures on this page are sample data.</p></div>{location !== "/earnings" && location !== "/profile" && location !== "/leaderboard" && <button className="btn btn-red" onClick={() => setModal(true)}><Plus size={15} /> Submit a clip</button>}</div>

      {(location === "/dashboard" || location === "/") && <>
        <section className="creator-top-grid"><div className="profile-banner"><div className="profile-banner-decoration" /><div className="profile-banner-main"><div className="creator-avatar">A</div><div><div className="creator-name">Alex Morgan <BadgeCheck size={14} /></div><div className="creator-handle">@alexmakes · member since Dec 2025</div><span className="approval-pill"><ShieldCheck size={11} /> Approval rate: 92%</span></div></div><div className="profile-stats-row"><div><span>Followers</span><strong>4K</strong></div><div><span>Linked pages</span><strong>5</strong></div><div><span>Campaigns</span><strong>3</strong></div></div></div><div className="creator-money-stack"><section className="earning-banner"><div><div className="earning-caption"><Coins size={13} /> Total earnings <span className="lime-dot" /></div><strong>{money(460.81)}</strong><div className="pending-line"><span className="amber-dot" /> Pending earnings <b>$0.00</b> <span className="sample-inline">sample</span></div></div><Link className="btn btn-lime btn-sm" href="/campaigns"><Search size={13} /> My campaigns</Link></section><div className="quick-stat-grid"><div className="quick-stat"><span>Total views</span><strong>248.6K</strong><div className="quick-stat-pills"><span className="lime-pill">↗ 233.8K</span><span className="gold-pill">◉ 0</span><span className="rose-pill">⌁ 14.7K</span></div></div><div className="quick-stat"><span>Submissions</span><strong>{13 + submissions.length}</strong><div className="quick-stat-pills"><span className="lime-pill">✓ 7</span><span className="gold-pill">◷ 0</span><span className="rose-pill">× 6</span></div></div></div></div></section>
        <section className="campaign-showcase"><div className="showcase-header"><div><h2>Active campaigns <span className="sample-inline">SAMPLE</span></h2><p>Choose a brief and make it your own.</p></div><Link href="/campaigns" className="showcase-link">View all <ArrowRight size={13} /></Link></div><div className="campaign-rail">{campaigns.slice(0, 5).map((item, index) => <Link href={`/campaigns/${item.id}`} className={`dash-campaign-card poster-${index % 5}`} key={item.id}><div className="dash-campaign-art" style={{ "--campaign-accent": item.accent } as React.CSSProperties}><span className="poster-category">{item.category}</span><div className="poster-orbit" /><div className="poster-title">{item.name}</div><div className="poster-subtitle">CREATOR BRIEF</div><div className="poster-platforms">{item.platforms.slice(0, 2).join(" · ")}</div></div><div className="dash-campaign-foot"><span><Wallet size={11} />${(item.remaining / 1000).toFixed(1)}K left</span><strong><Coins size={11} />${item.rate.toFixed(2)} <small>/1K</small></strong></div></Link>)}</div></section>
        <div className="overview-grid">{[["Available balance", "$426.80", "Ready to request · sample"], ["Pending review", "$142.15", "3 clips in review · sample"], ["Lifetime earned", "$2,841.60", "28 approved clips · sample"], ["Verified views", "186.4K", "Illustrative analytics"]].map(([label, value, note], index) => <div className="overview-card" key={label}><div className="overview-label"><span>{label}</span>{index === 0 ? <Wallet size={14} /> : index === 1 ? <Activity size={14} /> : index === 2 ? <Coins size={14} /> : <ShieldCheck size={14} />}</div><div className="overview-number">{value}</div><div className={`overview-note ${index === 0 ? "good" : ""}`}>{note}</div></div>)}</div>
        <div className="workspace-grid"><section className="panel"><div className="panel-head"><h2>View activity</h2><span>Last 7 days · illustrative</span></div><div className="bar-chart">{[[44,28],[59,39],[47,33],[72,45],[56,51],[88,62],[100,73]].map(([views, earned], index) => <div className="bar-group" key={index}><div className="bar-pair"><div className="bar" style={{ height: `${views}%` }} /><div className="bar accent" style={{ height: `${earned}%` }} /></div><div className="bar-label">{["M","T","W","T","F","S","S"][index]}</div></div>)}</div><div className="legend"><span><i />Estimated earnings</span><span><i />Views</span></div></section><section className="panel"><div className="panel-head"><h2>Recent clips</h2><Link className="inline-link" href="/clips">See all</Link></div><div className="clip-list">{allClips.slice(0, 3).map((item) => <div className="clip-row" key={item.id}><div><div className="clip-campaign">{item.campaign}</div><div className="clip-meta"><span>{item.platform}</span><span>{item.views.toLocaleString()} views</span></div></div><div><div className="clip-amount">{money(item.earned)}</div><div className="clip-status"><span className={`status ${item.status === "Approved" ? "approved" : item.status === "Tracking" ? "tracking" : item.status === "Rejected" ? "rejected" : "review"}`}>{item.status}</span></div></div></div>)}</div></section></div>
        <div className="workspace-grid"><section className="panel"><div className="panel-head"><h2>Recent activity</h2><span>Demo feed</span></div>{[["A clip passed human review", "Orbit Protocol · 18 min ago"], ["New brief matches your style", "Solstice · 2 hr ago"], ["View milestone reached", "Memehouse · Yesterday"]].map(([title, meta]) => <div className="activity-line" key={title}><span className="activity-mark"><ArrowUpRight size={13} /></span><div><strong>{title}</strong><small>{meta}</small></div></div>)}</section><section className="panel"><div className="panel-head"><h2>Trust status</h2><ShieldCheck size={16} color="#a6d900" /></div><div className="notice"><strong>Designed for real-view review.</strong><br />In a live product, linked-account ownership, rate limits, and anomaly signals would help reviewers assess each post. This demo does not connect to social platforms.</div><div style={{ marginTop: 13 }}><Link href="/review" className="btn btn-light btn-sm">Open trust review demo <ArrowRight size={13} /></Link></div></section></div>
      </>}

      {location === "/leaderboard" && <section className="panel leaderboard-panel"><div className="leaderboard-toolbar"><div><div className="panel-head" style={{ marginBottom: 6 }}><h2>Top creators</h2><Trophy size={15} color="#a6d900" /></div><span>Rankings are illustrative and reset by period in a live product.</span></div><div className="leader-actions"><div className="leader-tabs">{(["This week", "This month"] as const).map((period) => <button key={period} className={`leader-tab ${period === leaderPeriod ? "active" : ""}`} onClick={() => setLeaderPeriod(period)}>{period}</button>)}</div><button className={`connected ${anonymous ? "on" : ""}`} onClick={() => setAnonymous(!anonymous)}>{anonymous ? "Names hidden" : "Hide names"}</button></div></div><div className="leader-highlight"><div className="leader-medal">01</div><div><small>Creator of the {leaderPeriod.toLowerCase()}</small><strong>{anonymous ? "Creator #1" : leaderboard[0].handle}</strong></div><div className="leader-highlight-earn">{money(leaderboard[0].earned)} <small>sample earned</small></div></div><div className="table-wrap"><table className="data-table leader-table"><thead><tr><th>Rank</th><th>Creator</th><th>Approved clips</th><th>Views</th><th>Earned</th></tr></thead><tbody>{leaderboard.map((item, index) => <tr key={item.handle}><td><span className={`rank-number ${index < 3 ? "top-three" : ""}`}>{String(index + 1).padStart(2, "0")}</span></td><td><div className="leader-creator"><span className="profile-avatar">{anonymous ? "?" : item.name.slice(0, 1)}</span><strong>{anonymous ? `Creator #${index + 1}` : item.handle}</strong>{index === 4 && <span className="you-tag">YOU</span>}</div></td><td>{item.clips}</td><td>{item.views.toLocaleString()}</td><td><strong>{money(item.earned)}</strong></td></tr>)}</tbody></table></div><div className="notice" style={{ marginTop: 14 }}>Leaderboard visibility can be disabled or anonymized. All displayed ranks and earnings are fictional preview data.</div></section>}

      {location === "/clips" && <section className="panel"><div className="panel-head"><h2>All submitted clips</h2><span>{allClips.length} sample and demo submissions</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Clip</th><th>Campaign</th><th>Platform</th><th>Views</th><th>Est. earnings</th><th>Status</th><th>Submitted</th></tr></thead><tbody>{allClips.map((item) => <tr key={item.id}><td><strong>{item.id}</strong></td><td>{item.campaign}</td><td>{item.platform}</td><td>{item.views.toLocaleString()}</td><td>{money(item.earned)}</td><td><span className={`status ${item.status === "Approved" ? "approved" : item.status === "Tracking" ? "tracking" : item.status === "Rejected" ? "rejected" : "review"}`}>{item.status}</span></td><td>{item.submitted}</td></tr>)}</tbody></table></div><div className="notice" style={{ marginTop: 14 }}>In the live product, each eligible public post would need a connected platform-data integration before view totals could update. No real tracking runs here.</div></section>}

      {location === "/earnings" && <><div className="earnings-total"><small>Available to request · sample balance</small><strong>$426.80</strong><button className="btn btn-red btn-sm" onClick={requestPayout}><ArrowDownToLine size={14} /> Request payout</button></div><div className="earnings-grid"><div className="earnings-stat"><span>Pending approval</span><strong>$142.15</strong></div><div className="earnings-stat"><span>Lifetime earned</span><strong>$2,841.60</strong></div></div><section className="panel section-gap"><div className="panel-head"><h2>Earnings by clip</h2><span>Illustrative breakdown</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Campaign</th><th>Views reviewed</th><th>Rate</th><th>Earned</th><th>Status</th></tr></thead><tbody><tr><td><strong>Orbit Protocol</strong></td><td>28,400</td><td>$4.80 / 1K</td><td>$136.32</td><td><span className="status approved">Approved</span></td></tr><tr><td><strong>Memehouse</strong></td><td>19,200</td><td>$3.20 / 1K</td><td>$61.44</td><td><span className="status tracking">Tracking</span></td></tr><tr><td><strong>Solstice</strong></td><td>12,700</td><td>$5.50 / 1K</td><td>$69.85</td><td><span className="status review">Under review</span></td></tr></tbody></table></div><div className="notice" style={{ marginTop: 14 }}>Demo only: no wallet is connected, no payout request is submitted, and no funds are transferred.</div></section></>}

      {location === "/profile" && <div className="profile-grid"><section className="panel"><div className="panel-head"><h2>Linked social accounts</h2><span>Demo toggles only</span></div><p style={{ color: "#b1b2ad", fontSize: 10, lineHeight: 1.6 }}>A production account-ownership check needs a secure sign-in or platform-supported verification flow. Clicking these controls only changes this browser's preview.</p>{["TikTok","Instagram","YouTube","X"].map((platform) => <div className="social-row" key={platform}><span className="social-symbol">{platform === "YouTube" ? "Y" : platform === "Instagram" ? "◎" : platform[0]}</span><div className="social-copy">{platform}<small>{connected.includes(platform) ? "Demo connected state" : "Not connected"}</small></div><button className={`connected ${connected.includes(platform) ? "on" : ""}`} onClick={() => toggleSocial(platform)}>{connected.includes(platform) ? "Connected" : "Connect"}</button></div>)}</section><section className="panel"><div className="panel-head"><h2>Creator profile</h2><BadgeCheck size={16} color="#a6d900" /></div><div className="profile-chip" style={{ padding: "14px 0", border: 0 }}><div className="profile-avatar" style={{ width: 52, height: 52, fontSize: 17 }}>A</div><div><div className="profile-name" style={{ fontSize: 14 }}>Alex Morgan</div><div className="profile-level">@alexmakes · Sample creator profile</div></div></div><div className="earnings-grid"><div className="earnings-stat"><span>Total views</span><strong>186.4K</strong></div><div className="earnings-stat"><span>Approval rate</span><strong>92%</strong></div></div><div className="notice" style={{ marginTop: 14 }}><strong>Verified tier: preview state</strong><br />Real verification, creator tiers, referral rewards, and wallet connection are not activated in this demo.</div><div style={{ marginTop: 15 }}><Link className="btn btn-light btn-sm" href="/learn"><CircleHelp size={14} /> Account safety guide</Link></div></section></div>}
      <div className="workspace-footnote">Sample data only. Demo submissions and profile changes are stored in this browser; there is no live tracking or payout connection.</div>
    </main></div>{modal && <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setModal(false); }}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="submit-title"><div className="dialog-head"><h2 id="submit-title">Submit a clip</h2><button className="dialog-close" aria-label="Close dialog" onClick={() => setModal(false)}><X size={18} /></button></div><p>Paste the public link to your post and choose a sample campaign. This prototype stores the submission only in your browser; it will not fetch views or notify a reviewer.</p><form onSubmit={submitClip}><label className="form-label" htmlFor="clip-url">Public post URL</label><input id="clip-url" className="form-input" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.tiktok.com/@you/video/..." required /><div className="form-help">Supported link formats: TikTok, Instagram, YouTube, or X.</div><label className="form-label" htmlFor="clip-campaign">Campaign</label><select id="clip-campaign" className="form-input" value={selectedCampaign} onChange={(event) => setSelectedCampaign(event.target.value)}>{campaigns.map((item) => <option value={item.id} key={item.id}>{item.name} · sample</option>)}</select><div className="notice" style={{ marginTop: 14 }}>Submitting adds a local demo row with “Under review” status. It does not connect a social account or begin real view tracking.</div><button className="btn btn-red" type="submit" style={{ width: "100%", marginTop: 16 }}>Add demo submission <ArrowRight size={14} /></button></form></section></div>}{toast && <div className="toast" role="status">{toast}</div>}</div>;
}
